- src/main/java/com/jajaja/domain/cart/converter/CartConverter.java
- src/main/java/com/jajaja/domain/cart/service/CartCommandServiceImpl.java
- src/main/java/com/jajaja/domain/cart/service/CartCommonService.java
- src/main/java/com/jajaja/domain/cart/service/CartQueryServiceImpl.java
- src/main/java/com/jajaja/domain/coupon/dto/CouponConditionDto.java
- src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
- 회의에서 정했던 컨벤션대로 공통 서비스 부분 명칭 수정
- 에러 메시지 내용 수정
- 쿠폰 null 처리 확실히 진행
- closes #9
제가 테스트할 때는 쿠폰 관련 에러가 나지 않아서... 일단 coupon이 null일 때 처리를 진행하지 않도록 converter에 로직을 추가하였습니다.
> 🐛 fix: 쿠폰 관련 null 처리

- src/main/java/com/jajaja/domain/product/repository/ProductSalesRepositoryCustom.java
- src/main/java/com/jajaja/domain/product/repository/ProductSalesRepositoryImpl.java
- src/main/java/com/jajaja/domain/search/controller/SearchController.java
- src/main/java/com/jajaja/domain/search/dto/PopularSearchKeywordsResponseDto.java
- src/main/java/com/jajaja/domain/search/entity/Search.java
- src/main/java/com/jajaja/domain/search/entity/enums/SearchSort.java
- src/main/java/com/jajaja/domain/search/repository/SearchRepository.java
- src/main/java/com/jajaja/domain/search/repository/SearchRepositoryCustom.java
- src/main/java/com/jajaja/domain/search/repository/SearchRepositoryCustomImpl.java
- src/main/java/com/jajaja/domain/search/service/SearchService.java
- src/main/java/com/jajaja/domain/search/service/SearchServiceImpl.java
- src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/jajaja/global/config/security/SecurityConfig.java
- 홈의 상품 검색 API, 인기 검색어 조회 API 등 검색 관련 API를 구현했습니다.
- closes #26
> ✨ feat: 홈 검색 관련 API 구현

- src/main/java/com/jajaja/domain/review/controller/ReviewController.java
- src/main/java/com/jajaja/domain/review/dto/response/PagingReviewImageListResponseDto.java
- src/main/java/com/jajaja/domain/review/dto/response/ReviewImageListDto.java
- src/main/java/com/jajaja/domain/review/repository/ReviewImageRepositoryCustom.java
- src/main/java/com/jajaja/domain/review/repository/ReviewImageRepositoryImpl.java
- src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
- src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
- 사진 리뷰 상세 조회 API 구현했습니다.
- closes #21 
> ✨ feat: 사진 리뷰 상세 조회 API 구현

- src/main/java/com/jajaja/domain/team/repository/TeamRepositoryCustom.java
- src/main/java/com/jajaja/domain/team/repository/TeamRepositoryImpl.java
- src/main/java/com/jajaja/domain/team/service/TeamCommandServiceImpl.java
- src/main/java/com/jajaja/domain/team/service/TeamCommonService.java
- src/main/java/com/jajaja/global/scheduler/TeamExpireScheduler.java
- 팀 매칭 상태에 따른 알림 전송하는 기능을 추가했습니다.
- closes #45 
- 알림 메시지는 임의로 작성해두었습니다. 더 좋은 메시지가 있다면 추천 부탁드립니다!
> ♻️ refactor: 팀 매칭 상태에 따른 알림 전송

- src/main/java/com/jajaja/domain/order/repository/OrderProductRepository.java
- src/main/java/com/jajaja/domain/review/controller/ReviewController.java
- src/main/java/com/jajaja/domain/review/dto/request/ReviewCreateRequestDto.java
- src/main/java/com/jajaja/domain/review/dto/response/ReviewCreateResponseDto.java
- src/main/java/com/jajaja/domain/review/service/ReviewCommandService.java
- src/main/java/com/jajaja/domain/review/service/ReviewCommandServiceImpl.java
- src/main/java/com/jajaja/domain/team/repository/TeamRepositoryCustom.java
- src/main/java/com/jajaja/domain/team/repository/TeamRepositoryImpl.java
- src/main/java/com/jajaja/domain/team/service/TeamCommandServiceImpl.java
- src/main/java/com/jajaja/domain/team/service/TeamCommonService.java
- src/main/java/com/jajaja/global/S3/controller/S3Controller.java
- src/main/java/com/jajaja/global/S3/dto/request/PresignedUploadListRequestDto.java
- src/main/java/com/jajaja/global/S3/dto/request/PresignedUploadRequestDto.java
- src/main/java/com/jajaja/global/S3/dto/response/PresignedUrlUploadListResponseDto.java
- src/main/java/com/jajaja/global/S3/dto/response/PresignedUrlUploadResponseDto.java
- src/main/java/com/jajaja/global/S3/service/S3Service.java
- src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/jajaja/global/scheduler/TeamExpireScheduler.java
- 구매한 상품에 대한 리뷰를 작성하는 API를 구현했습니다.
- closes #27
혹시라도 잘못된 부분이 있다면 말씀해주세요 바로 수정하겠습니다 ! ☺️
> ✨ feat: 리뷰 추가 API 구현

- src/main/java/com/jajaja/domain/review/controller/ReviewController.java
- src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryCustom.java
- src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
- src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
- src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
- src/main/java/com/jajaja/domain/team/controller/TeamController.java
- src/main/java/com/jajaja/domain/team/dto/response/TeamProductItemResponseDto.java
- src/main/java/com/jajaja/domain/team/dto/response/TeamProductListResponseDto.java
- src/main/java/com/jajaja/domain/team/repository/TeamRepositoryCustom.java
- src/main/java/com/jajaja/domain/team/repository/TeamRepositoryImpl.java
- src/main/java/com/jajaja/domain/team/service/TeamQueryService.java
- src/main/java/com/jajaja/domain/team/service/TeamQueryServiceImpl.java
- 게시판 관련 API를 구현했습니다.
- closes #62
- 전체 리뷰 조회
- 팀 모집 상품 목록 조회
> ✨ feat: 게시판 관련 API 구현

- src/main/java/com/jajaja/domain/review/controller/ReviewController.java
- src/main/java/com/jajaja/domain/review/dto/response/PagingReviewableOrderListResponseDto.java
- src/main/java/com/jajaja/domain/review/dto/response/ReviewableOrderItemDto.java
- src/main/java/com/jajaja/domain/review/dto/response/ReviewableOrderListDto.java
- src/main/java/com/jajaja/domain/review/entity/Review.java
- src/main/java/com/jajaja/domain/review/repository/ReviewRepository.java
- src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryCustom.java
- src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
- src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
- src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
- 리뷰 작성 상품 목록 조회 API를 구현했습니다.
- closes #72
> ✨ feat: 리뷰 작성 목록 조회 API 구현

- src/main/java/com/jajaja/global/config/CorsConfig.java
- src/main/java/com/jajaja/global/config/security/SecurityConfig.java
- src/main/resources/application.yml
- CORS 설정 추가
- closes #77 
- application.yml 수정되었습니다
- 지금은 localhost:3000만 등록해놨고, 프론트 배포 후에 추가할 예정입니다
- 승인 후 바로 main까지 머지하겠습니다
> ✨ feat: CORS 설정 추가

- src/main/java/com/jajaja/global/config/security/jwt/JwtProvider.java
- 쿠키 sameSite, secure 설정 추가
- closes #80 
- 일단 미리 해놨는데 프론트 답변 보고 머지하겠습니다!
> ✨ feat: 쿠키 sameSite, secure 설정 추가

- src/main/java/com/jajaja/global/config/security/jwt/JwtProvider.java
> 🚀 deploy: dev -> main 병합

- src/main/java/com/jajaja/domain/cart/controller/CartController.java
- src/main/java/com/jajaja/domain/coupon/controller/CouponController.java
- src/main/java/com/jajaja/domain/order/controller/OrderController.java
- src/main/java/com/jajaja/domain/product/controller/ProductController.java
- src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
- src/main/java/com/jajaja/domain/review/controller/ReviewController.java
- src/main/java/com/jajaja/global/S3/controller/S3Controller.java
- src/main/java/com/jajaja/global/apiPayload/exception/ExceptionAdvice.java
- 홈 상품 조회 관련 null 방어적 처리
- controller summary, description 오타 수정 및 포맷 통일
- JSON 포맷 관련 에러 처리 추가
- closes #86 
처음엔 버그라고 생각해서 브랜치를 bug/.. 로 땄는데 버그라기보단 리팩토링에 가까운 것 같아 제목을 refactoring으로 작성했습니다..🥹
> ♻️ refactor: null 처리, controller 관련 변경, 에러 처리 추가

- src/main/java/com/jajaja/global/config/security/jwt/JwtProvider.java
- src/main/resources/application.yml
- 코드 변경 없이 환경변수 설정으로 sameSite, secure 설정할 수 있도록 수정
> ✨ feat: 쿠키 설정을 동적으로 변경

- src/main/java/com/jajaja/domain/auth/controller/AuthController.java
- src/main/java/com/jajaja/domain/auth/dto/CustomOAuth2User.java
- src/main/java/com/jajaja/domain/auth/dto/MemberDto.java
- src/main/java/com/jajaja/domain/auth/service/AuthService.java
- src/main/java/com/jajaja/domain/auth/service/CustomOAuth2UserService.java
- src/main/java/com/jajaja/domain/member/controller/MemberBusinessCategoryController.java
- src/main/java/com/jajaja/domain/member/service/MemberBusinessCategoryCommandService.java
- src/main/java/com/jajaja/domain/member/service/MemberBusinessCategoryCommandServiceImpl.java
- src/main/java/com/jajaja/domain/order/controller/OrderController.java
- src/main/java/com/jajaja/domain/order/dto/response/OrderItemProductDto.java
- src/main/java/com/jajaja/domain/order/service/OrderQueryService.java
- src/main/java/com/jajaja/domain/order/service/OrderQueryServiceImpl.java
- src/main/java/com/jajaja/domain/product/controller/ProductController.java
- src/main/java/com/jajaja/domain/product/entity/BusinessCategory.java
- src/main/java/com/jajaja/domain/product/service/ProductQueryService.java
- src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
- src/main/java/com/jajaja/domain/review/repository/ReviewLikeRepositoryCustom.java
- src/main/java/com/jajaja/domain/review/repository/ReviewLikeRepositoryImpl.java
- src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
- src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
- src/main/java/com/jajaja/global/config/security/jwt/JwtProvider.java
- src/main/java/com/jajaja/global/config/security/resolver/AuthArgumentResolver.java
- user 명칭을 전부 member로 통일하였습니다.
- closes #92 
> ♻️ refactor: member 명칭 통일

- .github/workflows/ci-cd-local.yml
- .github/workflows/ci-cd.yml
- ci-cd.yml 브랜치 수정하였습니다.
- closes #107 
> ♻️ refactor: ci-cd.yml 브랜치 수정

- src/main/java/com/jajaja/domain/notification/controller/NotificationController.java
- src/main/java/com/jajaja/domain/notification/dto/request/NotificationCreateRequestDto.java
- src/main/java/com/jajaja/domain/notification/dto/response/NotificationResponseDto.java
- src/main/java/com/jajaja/domain/notification/dto/response/PagingNotificationResponseDto.java
- src/main/java/com/jajaja/domain/notification/dto/response/UnreadCountResponseDto.java
- src/main/java/com/jajaja/domain/notification/repository/NotificationRepositoryCustom.java
- src/main/java/com/jajaja/domain/notification/repository/NotificationRepositoryImpl.java
- src/main/java/com/jajaja/domain/notification/service/NotificationService.java
- src/main/java/com/jajaja/domain/notification/service/NotificationServiceImpl.java
- src/main/java/com/jajaja/domain/team/service/TeamCommonService.java
- src/main/java/com/jajaja/global/scheduler/PointExpireScheduler.java
- src/main/java/com/jajaja/global/scheduler/TeamExpireScheduler.java
- 알림 목록 조회 API 페이징 추가
- closes #116 
> ✨ Feat: 알림 목록 조회 API 페이징 추가

- src/main/java/com/jajaja/domain/member/service/MemberQueryService.java
- src/main/java/com/jajaja/domain/member/service/MemberQueryServiceImpl.java
- src/main/java/com/jajaja/domain/product/dto/response/ProductDetailResponseDto.java
- src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
- src/main/java/com/jajaja/domain/review/dto/response/ReviewItemDto.java
- src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
- src/main/java/com/jajaja/domain/team/dto/response/TeamListDto.java
- 프로필 Keyname 전달할 수 있도록 DTO 수정합니다.
- closes #119 
> ♻️ refactor: 프로필 Keyname 전달할 수 있도록 DTO 수정

- src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
- 리뷰 상세 조회 API에 이미지 정적 URL 변환 적용하였습니다.
- closes #127 
> ♻️ refactor: 리뷰 상세 조회 API에 이미지 정적 URL 변환 적용

- src/main/java/com/jajaja/domain/auth/controller/AuthController.java
- src/main/java/com/jajaja/domain/cart/controller/CartController.java
- src/main/java/com/jajaja/domain/coupon/controller/CouponController.java
- src/main/java/com/jajaja/domain/delivery/controller/DeliveryController.java
- src/main/java/com/jajaja/domain/member/controller/MemberBusinessCategoryController.java
- src/main/java/com/jajaja/domain/member/controller/MemberController.java
- src/main/java/com/jajaja/domain/notification/controller/NotificationController.java
- src/main/java/com/jajaja/domain/order/controller/OrderProductsController.java
- src/main/java/com/jajaja/domain/point/controller/PointController.java
- src/main/java/com/jajaja/domain/product/controller/CategoryController.java
- src/main/java/com/jajaja/domain/product/controller/ProductController.java
- src/main/java/com/jajaja/domain/review/controller/ReviewController.java
- src/main/java/com/jajaja/domain/search/controller/SearchController.java
- src/main/java/com/jajaja/domain/team/controller/TeamController.java
- src/main/java/com/jajaja/global/S3/controller/S3Controller.java
- src/main/java/com/jajaja/global/common/health/HealthController.java
- Swagger 태그 문서화 통일 작업
- closes #131 
@tl1l1l1s 아직 수정할 부분이 남은 것 같아 보이셔서, 제가 전체 컨트롤러 수정 작업했습니다!
> ♻️ refactor: Swagger 태그 문서화 통일 작업

- src/main/java/com/jajaja/domain/search/controller/SearchController.java
- src/main/java/com/jajaja/domain/search/dto/PagingSearchProductListResponseDto.java
- src/main/java/com/jajaja/domain/search/repository/SearchRepositoryCustom.java
- src/main/java/com/jajaja/domain/search/repository/SearchRepositoryCustomImpl.java
- src/main/java/com/jajaja/domain/search/service/SearchService.java
- src/main/java/com/jajaja/domain/search/service/SearchServiceImpl.java
- 상품 검색 API 페이징 추가
- closes #135
문제 있으면 알려주세요!
> ✨ Feat: 상품 검색 API 페이징 추가

- src/main/java/com/jajaja/domain/order/service/OrderCommandServiceImpl.java
- src/main/java/com/jajaja/global/config/TossPaymentsConfig.java
- config 명칭 관련 에러 수정
- closes #이슈번호
> 🐛 fix: config 명칭 에러 수정
